name: Site Checks
on:
  pull_request:
    branches: [ main ]

jobs:
  muffet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install caddy
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release --repo caddyserver/caddy download -p 'caddy*linux_amd64.tar.gz' --output caddy.tar.gz
          tar xvf caddy.tar.gz caddy
          sudo mv caddy /usr/local/bin
      - run: caddy start
      - name: Install muffet
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release --repo raviqqe/muffet download -p muffet_linux_amd64.tar.gz
          tar xvf muffet_linux_amd64.tar.gz muffet
          sudo mv muffet /usr/local/bin
      - name: check links with muffet
        run: |
          muffet http://localhost:2015 \
            --buffer-size=8192 \
            --exclude="https://twitter\.com"
      - run: caddy stop
        if: always()
